spring:
  profiles:
    active:
      - DBDataSource
      - inMemoryDB
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  baseUrl: http://localhost:8080/
  imageUrl: student/images/
  imageServerDir: c:/bitbucket/images/
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
---
spring:
  profiles: inMemoryDB
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
---
spring:
  profiles: local
server:
  baseUrl: http://localhost:1000/
  imageUrl: images/
---
spring:
  profiles: remote
server:
  baseUrl: https://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl: pics/